name: Release & Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*' # Runs only when a tag like v1.2.3 is pushed
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Publish to npm using JS-DevTools/npm-publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      
      - name: End message
        run: echo "🎉 Released!"